---
title: "Make a Plot"
---

## How ggplot Works

Perhaps this section should be how `plotnine` works, but `ggplot()` (or `.ggplot()` still applies, so I keep the original section title from @Healy2026.
Everything from [the original section](https://socviz.co/03-ggplot-basics.html#how-ggplot-works) applies here.

## Tidy Data

While the term **tidy data** comes from @Wickham2014 and is therefore perhaps more often associated with R, it describes ideas that predate @Wickham2014 and applies equally well to Python Polars.

## Mappings Link Data to Things You See

Here I follow @Healy2026 in using the `gapminder` data set.
While @Healy2026 accesses this data set using `library(gapminder)`, I get it from the GitHub page for that R package.

```{python}
import polars as pl
from plotnine_polars import ggplot, aes

gapminder = pl.read_csv(
    "https://raw.githubusercontent.com/jennybc/gapminder/main/inst/extdata/gapminder.tsv",
    separator="\t"
)
```

From the following code, we see that we have the same data as are shown in @Healy2026.

```{python}
gapminder.head(10)
```

We imported `ggplot()` above as a function.
If we follow the R approach and access this function directly, we need to tell the function what data we want to use.

```{python}
p = ggplot(data=gapminder)
```

However, an alternative approach uses the fact that `plotnine_polars` added a `.ggplot()` method where it is clear what data set we want to use.

```{python}
p = gapminder.ggplot()
```

@Healy2026 says: "At this point ggplot knows our data, but not ... the *mapping*.
That is, we need to tell it which variables in the data should be represented by which visual elements in the plot. ... In ggplot, mappings are specified using the `aes()` function."
We can use the same approach with `plotnine` because we have imported `aes()`.

```{python}
p = (
    gapminder
    .ggplot(aes(x="gdpPercap", y="lifeExp"))
)
```

As an alternative, we can use the `.aes()` method created by `plotnine_polars` as follows.

```{python}
p = (
    gapminder
    .ggplot(aes(x="gdpPercap", y="lifeExp"))
)
```

As in @Healy2026, if we type `p` as the console, we get the result seen below.

```{python}
p
```

As discussed by @Healy2026, the issue is that "We haven't yet given p any instructions about what sort of plot to draw with the information it has.
We need to add a *layer* to the plot.
This means picking a `geom_` function.
We will use `geom_point()`.
It knows how to take `x` and `y` values and plot them in a scatterplot."

With `plotnine_polars` it is more natural to use the `.geom_point()` method instead of importing and using the `geom_point()` function.
The result from doing so is seen in @fig-ch-03-fig-lexp-gdp-01.

```{python}
#| label: fig-ch-03-fig-lexp-gdp-01
#| fig-cap: A scatterplot of Life Expectancy vs GDP.
p.geom_point()
```

```{python}
(
    gapminder
    .ggplot(aes(x="gdpPercap",y="lifeExp"))
    .geom_smooth(method="loess")
)
```

```{python}
p = gapminder.ggplot(aes(x="gdpPercap", y="lifeExp"))

p.geom_point().geom_smooth(method="loess")
```

```{python}
p = gapminder.ggplot(aes(x="gdpPercap", y="lifeExp"))

p.geom_point().geom_smooth(method="lm")
```

```{python}
p = gapminder.ggplot(aes(x="gdpPercap", y="lifeExp"))

(
    p
    .geom_point()
    .geom_smooth(method="loess", color="blue")
    .scale_x_log10()
)
```

Now skip creating `p`.

```{python}
(
    gapminder
    .ggplot(aes(x="gdpPercap", y="lifeExp"))
    .geom_point()
    .geom_smooth(method="loess", color="blue")
    .scale_x_log10()
)
```

```{python}
(
    gapminder
    .ggplot(aes(x="gdpPercap", y="lifeExp"))
    .geom_point()
    .geom_smooth(method="loess", colour="blue")
    .scale_x_log10()
)
```

```{python}
from mizani.formatters import currency_format

p = gapminder.ggplot(aes(x="gdpPercap", y="lifeExp"))

(
    p
    .geom_point()
    .geom_smooth(method="loess")
    .scale_x_log10(labels=currency_format(precision=0, big_mark=','))
)
```

```{python}
(
    gapminder
    .ggplot(aes(x="gdpPercap", y="lifeExp", color='"purple"'))
    .geom_point()
    .geom_smooth(method="loess")
    .scale_x_log10()
)
```

```{python}
(
    gapminder
    .ggplot(aes(x="gdpPercap", y="lifeExp"))
    .geom_point(color="purple")
    .geom_smooth(method="loess")
    .scale_x_log10()
)
```

```{python}
(
    gapminder
    .ggplot(aes(x="gdpPercap", y="lifeExp"))
    .geom_point(alpha=0.3)
    .geom_smooth(color="firebrick", se=False,
                 size=8,  # not linewidth
                 method="lm")
    .scale_x_log10()
)
```

```{python}
(
    gapminder
    .ggplot(aes(x="gdpPercap", y="lifeExp"))
    .geom_point(alpha=0.3)
    .geom_smooth(method="loess", se=False)
    .scale_x_log10(labels=currency_format(precision=0, big_mark=','))
    .labs(x="GDP Per Capita", y="Life Expectancy in Years",
          title="Economic Growth and Life Expectancy",
          subtitle="Data points are country-years",
          caption="Source: Gapminder.")
)
```

```{python}
(
    gapminder
    .ggplot()
    .aes(x="gdpPercap", y="lifeExp", color="continent")
    .geom_point()
    .geom_smooth(method="loess", se=False)
    .scale_x_log10()
)
```

```{python}
(
    gapminder
    .ggplot(aes(x="gdpPercap", y="lifeExp", 
                color="continent", fill="continent"))
    .geom_point()
    .geom_smooth(method="loess")
    .scale_x_log10()
)
```

```{python}
from plotnine_polars import aes

(
    gapminder
    .ggplot(aes(x="gdpPercap", y="lifeExp"))
    .geom_point(aes(color="continent"))
    .geom_smooth(method="loess")
    .scale_x_log10()
)
```

```{python}
import numpy as np
```

```{python}
(
    gapminder
    .with_columns(log_pop=pl.col("pop").log())
    .ggplot(aes(x="gdpPercap", y="lifeExp", color="log_pop"))
    .geom_point()
    .scale_x_log10()
)
```

```{python}
p_out = (
    gapminder
    .ggplot(aes(x="gdpPercap", y="lifeExp"))
    .geom_point()
    .geom_smooth(method="loess")
    .scale_x_log10()
)
```

```{python}
#| warning: false
p_out.save("lifexp_vs_gdp_gradient.pdf", 
           height=8, width=10, units="in")
```


```{python}
from plotnine.data import mpg

mpg = pl.from_pandas(mpg)
```

```{python}
(
    mpg
    .ggplot(aes(x="displ", y="hwy"))
    .geom_point()
    .geom_smooth(method="loess")
    .labs(x="displacement", y="horsepower")
)
```
