project:
  type: book
  output-dir: _book

book:
  title: "Data Visualization: A Python/Polars Companion"
  author: "Ian Gow"
  chapters:
    - index.qmd
    - 01-look-at-data.qmd
    - 02-intro.qmd
    - 03-ggplot-basics.qmd
    - 04-group-facet-transform.qmd
    - 05-more-on-geoms.qmd
    - 06-modeling.qmd
    - 07-maps.qmd
  appendices:
    - appendix-map-data.qmd

format:
  html:
    theme: cosmo
    toc: true
    mainfont: "EB Garamond"
    sansfont: "Source Sans 3"
    monofont: "JetBrains Mono"
    css: custom.css

bibliography: references.bib

execute:
  freeze: auto
  keep-ipynb: false

publish:
  gh-pages:
    branch: gh-pages
